alias white='totem ~/Videos/white.mp4'
alias v='nvim'
alias vc='nvim /tmp/command.txt'
alias dot='cd ~/dotfiles'
alias rm='rm -i'
alias mv='mv -i'

alias pro='cd ~/cbetadir/src'
alias not='cd ~/notes && gp'
alias dot='cd ~/dotfiles'

alias tls='tmux ls'
alias tkill='tmux kill-session -t'
alias tas='tmux attach-session -t'
alias ta='tmux a'

alias lsa='ls -a'
alias py='python3'
alias c='clear'
alias update='sudo apt-get update -y && sudo apt-get upgrade -y'
alias shut='sudo shutdown -h now'
alias restart='sudo shutdown -r now'

alias gp='git pull'
alias gh='git push'
alias gpp='git pull && git push'
alias gs='clear && git status'
alias gc='git commit'
alias ga='git add'
alias go='git checkout'
alias gd='git diff'
alias grr='git reset --hard & git fetch --all & git pull'
