alias py='python3'

alias un='cd ~/Documents/Projects/uncountable_repamtrick/'
alias papers='cd ~/Documents/Papers/'
alias gre='cd ~/Documents/Personal/GRE/gre/'
alias white='open ~/Pictures/White\ Noise.mp4'
alias tkill='tmux kill-session -t 0'

alias c='clear'
alias z='zathura'
alias speed='speedtest-cli'
alias shut='sudo shutdown -h now'
alias restart='sudo shutdown -r now'

alias gp='git pull'
alias gpp='git push'
alias gs='git status'
alias gc='git commit'
alias ga='git add'

alias glist='gcloud compute instances list'
alias gssh='gcloud compute ssh apotapczynski@$vm'
alias gstart='gcloud compute instances start $vm'
alias gstop='gcloud compute instances stop $vm'
alias gscp='gcloud compute scp --recurse apotapczynski@$vm:~/uncountable_repamtrick/Log ~/Downloads'
