syn match textComment "\"\_.\{-}\""
syn match textComment2 "\`\_.\{-}\`"
syn match textUnderline "<\_.\{-}>"
syn match textAr "@\((\_.\{-})\)"
syn match textCode "\$\[\_.\{-}\]"
syn match textTitle1 "%%%%.*$"
syn match textTitle2 "##.*$"
syn match textBullet "*\s"
