require('ap.maps')
require('ap.packer')
require('ap.lsp')
require('ap.cmp')
require('ap.status')
require('ap.signature')
require('ap.tree')
require('ap.teles')
require('ap.slime')

vim.cmd.colorscheme("tokyonight")
