require("ap.maps")
require("ap.autocmd")
require("ap.packer")
require("ap.lsp")
require("ap.cmp")
require("ap.status")
require("ap.tree")
require("ap.signature")
require("ap.teles")

vim.cmd.colorscheme("tokyonight")
